"""
monday_app.py  —  MONDAY: drive the car by hand, RECORD pictures, and (once you
have a trained model) try Autodetect. You do NOT edit this file — you edit detect.py.

Run:   python monday_app.py
Controls:
  - Hold the UP ARROW to drive forward (let go to stop).
  - Click "Record" to start saving camera pictures into the 'frames' folder;
    click again to stop. Resuming keeps the old pictures and adds new ones.
  - Click "Autodetect" (only works after you have a model) to see live labels.
  - Press Q to quit.
"""
import os, glob, pygame
from sim import TrafficWorld
import ui
from tm_model import load_interpreter, load_labels, input_size, predict
from detect import predict_label

MODEL = "model_unquant.tflite"
LABELS = "labels.txt"
FRAMES_DIR = "frames"      # recorded pictures go here
REC_EVERY = 3              # save 1 of every 3 frames while recording
MANUAL_SPEED = 4.0


def next_index(folder):
    os.makedirs(folder, exist_ok=True)
    nums = []
    for p in glob.glob(os.path.join(folder, "frame_*.png")):
        try:
            nums.append(int(os.path.basename(p)[6:-4]))
        except ValueError:
            pass
    return (max(nums) + 1) if nums else 0


def main():
    # A model may not exist yet (you make it later today). That's fine.
    model = labels = None
    size = 224
    if os.path.exists(MODEL):
        try:
            model = load_interpreter(MODEL)
            labels = load_labels(LABELS)
            size = input_size(model)
            print("Model loaded. Classes:", labels)
        except Exception as e:
            print("Could not load model:", e)
            model = None

    world = TrafficWorld(title="Monday — capture data & detect")
    autodetect = ui.Button(20, 15, 175, 34, "Autodetect: OFF", enabled=(model is not None))
    record = ui.Button(210, 15, 230, 34, "Record")
    buttons = [autodetect, record]

    idx = next_index(FRAMES_DIR)
    saved_this_run = 0
    framecount = 0
    running = True
    while running:
        for e in pygame.event.get():
            if e.type == pygame.QUIT or (e.type == pygame.KEYDOWN and e.key == pygame.K_q):
                running = False
            elif e.type == pygame.MOUSEBUTTONDOWN:
                if autodetect.clicked(e.pos):
                    autodetect.on = not autodetect.on
                if record.clicked(e.pos):
                    record.on = not record.on

        keys = pygame.key.get_pressed()
        target = MANUAL_SPEED if keys[pygame.K_UP] else 0.0
        world.update()
        world.apply(target, 0)
        world.render_scene()
        crop = world.get_crop_array(size)

        # --- detection (shows a label, does NOT drive on Monday) ---
        if model is not None and autodetect.on:
            label = predict_label(predict(model, crop), labels)
            det = f"Detection: {label}"
            autodetect.text = "Autodetect: ON"
        else:
            det = "Detection: OFF (train a model first)" if model is None else "Detection: OFF"
            autodetect.text = "Autodetect: OFF"

        # --- recording ---
        if record.on:
            record.text = "Recording... (click to stop)"
            framecount += 1
            if framecount % REC_EVERY == 0:
                world.save_crop(os.path.join(FRAMES_DIR, f"frame_{idx:05d}.png"))
                idx += 1
                saved_this_run += 1
        else:
            record.text = "Record"

        # --- draw everything on top (the model never sees these) ---
        world.draw_camera_box()
        ui.draw_buttons(world.surface, buttons)
        drive = "DRIVING (UP held)" if target > 0 else "stopped — hold UP arrow to drive"
        ui.draw_statusbar(world.surface, [
            f"Manual: {drive}     |     {det}",
            f"Pictures in '{FRAMES_DIR}/': {idx}   (saved this run: {saved_this_run})     |     Q to quit",
        ])
        if not world.headless:
            pygame.display.flip()
        world.clock.tick(30)

    pygame.quit()
    print(f"\nDone. {idx} pictures are in '{FRAMES_DIR}/'.")
    print("Next: sort them into class folders (Stop, Speed25, Speed55, Red, Green, Nothing) and train in Teachable Machine.")


if __name__ == "__main__":
    main()
