"""
wednesday_app.py  —  WEDNESDAY: drive the car MANUALLY, or let your model drive it.
You do NOT edit this file. You edit  detect.py  (the Debouncer) and  brain.py  (the Controller).

Run (normal):        python wednesday_app.py
    - Mode button: MANUAL (hold UP to drive) / AUTO (your model drives; gray until a model is here).
    - Record button: save camera pictures into 'frames/' (like Monday). Resumes without overwriting.
    - Q to quit.

Extra modes (see the README):
    python wednesday_app.py --test-flickering     # a debouncer test bench (no model needed)
    python wednesday_app.py --hit-with-reality     # weather/condition buttons + a Score button
"""
import argparse, os, glob, time
import pygame
from sim import TrafficWorld, CROP
import ui
import conditions
from tm_model import load_interpreter, load_labels, input_size, predict
from detect import predict_label, Debouncer
from brain import Controller

MODEL = "model_unquant.tflite"
LABELS = "labels.txt"
FRAMES_DIR = "frames"
REC_EVERY = 3
MANUAL_SPEED = 4.0
SCORE_SECONDS = 120        # a scoring run lasts 2 minutes


def next_index(folder):
    os.makedirs(folder, exist_ok=True)
    nums = []
    for p in glob.glob(os.path.join(folder, "frame_*.png")):
        try:
            nums.append(int(os.path.basename(p)[6:-4]))
        except ValueError:
            pass
    return (max(nums) + 1) if nums else 0


def load_model():
    if not os.path.exists(MODEL):
        return None, None, 224
    try:
        m = load_interpreter(MODEL)
        return m, load_labels(LABELS), input_size(m)
    except Exception as e:
        print("Could not load model:", e)
        return None, None, 224


# =====================================================================
#  TEST BENCH:  --test-flickering
#  Feeds a scripted, flickering label stream into YOUR Debouncer so you can
#  watch it reject the flicker and only change on a solid run of 4+.
# =====================================================================
def run_flicker_test():
    world = TrafficWorld(title="Debouncer test bench — flickering")
    debouncer = Debouncer()
    controller = Controller()
    # one label per frame (we run slowly). Solid runs commit; flicker does not.
    seq = (["Speed55"] * 6
           + ["Speed55", "Speed25"] * 4     # flicker (never 4 in a row) -> action stays Speed55
           + ["Speed25"] * 6                # solid -> action becomes Speed25
           + ["Speed25", "Stop"] * 4)       # flicker -> action stays Speed25
    short = lambda L: L.replace("Speed", "")
    i = 0
    running = True
    while running:
        for e in pygame.event.get():
            if e.type == pygame.QUIT or (e.type == pygame.KEYDOWN and e.key == pygame.K_q):
                running = False

        raw = seq[i % len(seq)]
        world.signs = [{"kind": raw, "y": CROP.centery, "x": CROP.centerx, "scale": 1.0, "light": False}]
        world.render_scene()
        action = debouncer.add_frame(raw)
        speed = controller.decide_speed(action, time.time())

        world.draw_camera_box()
        window = "[" + ", ".join(short(x) for x in debouncer.observed_frames) + "]"
        ui.draw_statusbar(world.surface, [
            f"CAMERA sees (flickering):  {short(raw)}          window {window}",
            f"ACTION (steady):  {short(action)}          car speed {controller.speed_limit if speed > 0 else 0}          Q to quit",
        ])
        if not world.headless:
            pygame.display.flip()
        world.clock.tick(3)     # slow (~3 fps) so you can follow each frame change
        i += 1
    pygame.quit()


# =====================================================================
#  SCORER (used by the Score button in --hit-with-reality)
#  For every sign that passes the camera, checks whether the car's ACTION
#  matched the sign. Accuracy = signs handled correctly / signs seen.
# =====================================================================
class Scorer:
    def __init__(self):
        self.correct = 0
        self.total = 0
        self.current = None
        self.matched = False

    def update(self, world, action):
        in_box = [s for s in world.signs if CROP.top < s["y"] < CROP.bottom]
        sign = in_box[0] if in_box else None
        if sign is not self.current:                 # a sign just left / a new one arrived
            if self.current is not None:
                self.total += 1
                if self.matched:
                    self.correct += 1
            self.current = sign
            self.matched = False
        if sign is not None and action == sign["kind"]:
            self.matched = True

    def percent(self):
        return (100.0 * self.correct / self.total) if self.total else 0.0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--test-flickering", action="store_true", help="debouncer test bench")
    ap.add_argument("--hit-with-reality", action="store_true", help="weather conditions + scoring")
    args = ap.parse_args()

    if args.test_flickering:
        run_flicker_test()
        return

    model, labels, size = load_model()
    auto_enabled = model is not None
    world = TrafficWorld(title="Wednesday — self-driving car")
    debouncer = Debouncer()
    controller = Controller()

    mode = ui.Button(20, 15, 250, 34, "Mode: MANUAL", enabled=auto_enabled)
    record = ui.Button(290, 15, 190, 34, "Record")
    buttons = [mode, record]

    # ---- optional "hit with reality" extras ----
    cond_buttons = []
    slider = None
    score_btn = None
    condition = None
    if args.hit_with_reality:
        x = 20
        for name in conditions.NAMES:
            cond_buttons.append(ui.Button(x, 58, 82, 30, name))
            x += 90
        slider = ui.Slider(20, 104, 360, value=60, label="Harshness")
        score_btn = ui.Button(600, 104, 170, 34, "Score run", enabled=auto_enabled)

    idx = next_index(FRAMES_DIR)
    saved = 0
    framecount = 0
    dragging = False
    scoring = False
    score_end = 0.0
    last_score = None
    scorer = Scorer()

    running = True
    while running:
        now = time.time()
        for e in pygame.event.get():
            if e.type == pygame.QUIT or (e.type == pygame.KEYDOWN and e.key == pygame.K_q):
                running = False
            elif e.type == pygame.MOUSEBUTTONDOWN:
                if slider is not None and slider.grab(e.pos):
                    dragging = True
                    continue
                if mode.clicked(e.pos):
                    mode.on = not mode.on
                if record.clicked(e.pos):
                    record.on = not record.on
                if score_btn is not None and score_btn.clicked(e.pos):
                    scoring = True
                    scorer = Scorer()
                    score_end = now + SCORE_SECONDS
                    mode.on = True                      # scoring needs AUTO
                    score_btn.on = True
                for b in cond_buttons:
                    if b.clicked(e.pos):
                        condition = None if condition == b.text else b.text
                        for c in cond_buttons:
                            c.on = (c.text == condition)
            elif e.type == pygame.MOUSEMOTION and dragging and slider is not None:
                slider.grab(e.pos)
            elif e.type == pygame.MOUSEBUTTONUP:
                dragging = False

        keys = pygame.key.get_pressed()
        world.update()
        world.render_scene()
        if args.hit_with_reality and condition:
            conditions.apply(world.surface, condition, slider.value, world.frame, world)
        crop = world.get_crop_array(size) if model is not None else None

        if mode.on and auto_enabled:
            mode.text = "Mode: AUTO (self-driving)"
            raw_label = predict_label(predict(model, crop), labels)
            action = debouncer.add_frame(raw_label)
            speed = controller.decide_speed(action, now)
            world.apply(speed, 0)
            shown = controller.speed_limit if speed > 0 else 0
            det = f"sees {raw_label}   ->   action {action}   |   speed {shown}"
            if scoring:
                scorer.update(world, action)
        else:
            mode.text = "Mode: MANUAL (hold UP)" if auto_enabled else "Mode: MANUAL (no model for AUTO)"
            target = MANUAL_SPEED if keys[pygame.K_UP] else 0.0
            world.apply(target, 0)
            if model is not None:
                det = f"sees {predict_label(predict(model, crop), labels)}   (you are driving)"
            else:
                det = "no model — detection off   (you are driving)"

        # recording (works in any mode)
        if record.on:
            record.text = "Stop recording"
            framecount += 1
            if framecount % REC_EVERY == 0:
                world.save_crop(os.path.join(FRAMES_DIR, f"frame_{idx:05d}.png"))
                idx += 1
                saved += 1
        else:
            record.text = "Record"

        # end a scoring run
        if scoring and now >= score_end:
            scoring = False
            score_btn.on = False
            last_score = scorer.percent()

        # draw UI (on top — the model never sees these)
        world.draw_camera_box()
        ui.draw_buttons(world.surface, buttons + cond_buttons + ([score_btn] if score_btn else []))
        if slider is not None:
            slider.draw(world.surface)

        bits = []
        if args.hit_with_reality and condition:
            bits.append(f"{condition} {int(slider.value)}%")
        if record.on:
            bits.append(f"REC {saved}")
        if scoring:
            bits.append(f"SCORING  {int(score_end - now)}s left   {scorer.percent():.0f}%  ({scorer.correct}/{scorer.total})")
        elif last_score is not None:
            bits.append(f"last score {last_score:.0f}%")
        line2 = "     |     ".join(bits) if bits else "buttons above    |    hold UP to drive in manual    |    Q to quit"
        ui.draw_statusbar(world.surface, [det, line2])

        if not world.headless:
            pygame.display.flip()
        world.clock.tick(30)

    pygame.quit()


if __name__ == "__main__":
    main()
