"""
wednesday_app.py  —  WEDNESDAY: drive the car MANUALLY, or let the model drive it
(AUTO). You do NOT edit this file — you edit brain.py (the Controller).

Run:   python wednesday_app.py
Controls:
  - Click "Mode" to switch between MANUAL and AUTO.
      MANUAL: hold the UP ARROW to drive (let go to stop).
      AUTO:   the model drives the car (stop / go / speed / steer).
  - AUTO is disabled (gray) until a trained model is in this folder.
  - Press Q to quit.
"""
import os, pygame
from sim import TrafficWorld
import ui
from tm_model import load_interpreter, load_labels, input_size, predict
from brain import classify, Debouncer, Controller, CONFIDENCE_THRESHOLD, DEBOUNCE_FRAMES

MODEL = "model_unquant.tflite"
LABELS = "labels.txt"
MANUAL_SPEED = 4.0


def main():
    model = labels = None
    size = 224
    if os.path.exists(MODEL):
        try:
            model = load_interpreter(MODEL)
            labels = load_labels(LABELS)
            size = input_size(model)
            print("Model loaded. Classes:", labels)
        except Exception as e:
            print("Could not load model:", e)
            model = None
    auto_enabled = model is not None

    world = TrafficWorld(title="Wednesday — manual & self-driving")
    mode = ui.Button(20, 15, 280, 34, "Mode: MANUAL", enabled=auto_enabled)
    buttons = [mode]
    deb = Debouncer(DEBOUNCE_FRAMES)
    ctrl = Controller()

    running = True
    while running:
        for e in pygame.event.get():
            if e.type == pygame.QUIT or (e.type == pygame.KEYDOWN and e.key == pygame.K_q):
                running = False
            elif e.type == pygame.MOUSEBUTTONDOWN and mode.clicked(e.pos):
                mode.on = not mode.on        # toggle AUTO (only enabled if a model exists)

        keys = pygame.key.get_pressed()
        world.update()
        world.render_scene()
        crop = world.get_crop_array(size) if model is not None else None

        if mode.on and auto_enabled:
            # AUTO: the model drives
            mode.text = "Mode: AUTO (self-driving)"
            probs = predict(model, crop)
            label, conf = classify(probs, labels, CONFIDENCE_THRESHOLD)
            committed = deb.push(label)
            spd, steer = ctrl.update(committed)
            world.apply(spd, steer)
            det = f"sees {label} ({conf*100:.0f}%)  ->  {committed}   |   speed {ctrl.display_speed()}"
        else:
            # MANUAL: you drive with the UP arrow; the model only shows what it sees
            mode.text = "Mode: MANUAL (hold UP)" if auto_enabled else "Mode: MANUAL (no model for AUTO)"
            target = MANUAL_SPEED if keys[pygame.K_UP] else 0.0
            world.apply(target, 0)
            if model is not None:
                label, conf = classify(predict(model, crop), labels, CONFIDENCE_THRESHOLD)
                det = f"sees {label} ({conf*100:.0f}%)   (you are driving)"
            else:
                det = "no model — detection off   (you are driving)"

        world.draw_camera_box()
        ui.draw_buttons(world.surface, buttons)
        ui.draw_statusbar(world.surface, [
            det,
            "Click Mode = MANUAL/AUTO    |    hold UP to drive in manual    |    Q to quit",
        ])
        if not world.headless:
            pygame.display.flip()
        world.clock.tick(30)

    pygame.quit()


if __name__ == "__main__":
    main()
